name:                QuantumCalculator
version:             0.1.0.0
github:              "githubuser/QuantumCalculator"
license:             BSD3
author:              "Travis Ens"
maintainer:          "ens.travis@gmail.com"
copyright:           "2020 Travis Ens"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/QuantumCalculator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules: FreeLie

executables:
  QuantumCalculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuantumCalculator

tests:
  QuantumCalculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuantumCalculator
